Création de la librairie
CQEN-QDCE/ceai-cqen-terraform-lib pull request #2
Opened 2023-01-23 18:54 UTC by gagf01

Je voudrais vos commentaires sur la forme et les principes de la libraire. Des bugs vont être corrigé avec les premières utilisations (que je commence dans les prochains jours). 

Je sais c'est massif, je suis désolé, mais j'espère que ça jette la base de tous nos prochains déploiements Terraform. 

Merci à l'avance!

2023-01-26 21:26 UTC, PierreJiji requested changes

2023-01-27 20:31 UTC, gagf01 commented on aws/sea-ecs-fargate-service/main.tf
> +resource "aws_efs_file_system" "efs_fs" {
J'ai testé et si on fourni un map vide comme variable (la valeur par défaut), il ne crée rien.

2023-01-27 20:46 UTC, gagf01 commented on examples/aws-sea/main.tf
> +module "mysql" {
Les différents engins de BD ont juste assez de différences dans leur configuration que ça rend difficile de faire un module qui les gère tous. MySQL Aurora est une première proposition d'autres modules vont être rajoutés à mesure qu'on en a besoin.

2023-01-27 20:46 UTC, gagf01 commented on README.md
> +
Je ne connaissais pas ce dépôt, est-il encore pertinent?

2023-01-27 21:02 UTC, gagf01 commented on examples/aws-sea/tasks/task.json.tftpl
> +[
Il y a trop de particularité d'un déploiement à l'autre pour créer un "container definition" universel.

2023-01-27 21:07 UTC, gagf01 commented on README.md
> +module "ceai-lib" {
J'ai utilisé les tirets pour les noms de modules parce que j'ai vu que la plupart des modules utilisateurs les utilisaient: https://registry.terraform.io/browse/modules

2023-01-27 21:07 UTC, gagf01 commented on README.md
> +Les modules pour les ressources à déployer dans SEA sont presque tous dépendant du module `sea-network`. Celui-ci doit connaitre le nom du *OU* du compte du travail (Préfix du VPC partagé). L'utilisa
Même chose que ^

2023-01-27 21:09 UTC, gagf01 commented on aws/sea-ecs-fargate-service/main.tf
> +    matcher             = "200"
Ce bloc va être modifié, car Passbolt a un healthcheck non HTTP...

2023-01-27 21:11 UTC, gagf01 commented on README.md
> +Les modules pour les ressources à déployer dans SEA sont presque tous dépendant du module `sea-network`. Celui-ci doit connaitre le nom du *OU* du compte du travail (Préfix du VPC partagé). L'utilisa
f3a1c67

2023-01-27 21:11 UTC, gagf01 commented on aws/sea-ecs-fargate-service/README.md
> +| internal_endpoint_port | Port sur lequel est exposé le endpoint interne du service. (default = 443) |
f3a1c67

2023-01-27 21:11 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/README.md
> +| max_capacity | Capacité minimale provisionnée en ACU (Aurora Capacity Unit, 0,5ACU = 1GB RAM) |
f3a1c67

2023-01-27 21:12 UTC, gagf01 commented on README.md
> +
f3a1c67

2023-01-27 21:12 UTC, gagf01 commented on examples/aws-sea/README.md
> +```
f3a1c67

2023-01-27 21:12 UTC, gagf01 commented on README.md
> +}
f3a1c67

2023-01-31 21:09 UTC, PierreJiji commented on examples/aws-sea/main.tf
> +module "mysql" {
Comme nous utilisons souvent Postgres, ce serait probablement une bonne idée de l'ajouter, sauf si nous avons besoin d'utiliser Aurora.

2023-01-31 21:19 UTC, PierreJiji requested changes

2023-01-31 21:19 UTC, PierreJiji commented on README.md
> +module "ceai-lib" {
Super, c'est juste parce que j'ai vu que l'autre module est déclaré de la même façon sea_network et aussi le '-' me cause des problèmes parfois donc j'ai proposé '_'.  Mais je suis d'accord avec toi si tous les modules sont déclarés de la même façon.

2023-01-31 21:19 UTC, PierreJiji commented on aws/sea-ecs-fargate-service/main.tf
> +resource "aws_efs_file_system" "efs_fs" {
Est qu'il va créer de ressource EFS de toute façon ?

2023-01-31 21:25 UTC, PierreJiji commented on README.md
> +
> Je ne connaissais pas ce dépôt, est-il encore pertinent?
Nous avons utilisé ce dépôt pour ajouter des formations pour notre laboratoire et nous avons commencé avec un script Terraform pour déployer EC2, et il a été utilisé par plusieurs membres de notre équipe. Nous pouvons réfléchir à la manière d'organiser nos dépôts afin d'éviter les doublons ou de faciliter la navigation entre nos dépôts sur GitHub.

2023-02-02 19:19 UTC, yonepv approved these changes

2023-02-03 21:02 UTC, gagf01 commented on aws/sea-ecs-fargate-service/main.tf
> +resource "aws_efs_file_system" "efs_fs" {
Non

2023-02-23 20:41 UTC, gagf01 commented on README.md
> +module "ceai-lib" {
c38c5b1

2023-03-22 19:35 UTC, PierreJiji approved these changes

2023-03-22 19:36 UTC, merged