Feature/backup rds aurora + Integrer les modules Network + RDS avec EKS
CQEN-QDCE/ceai-cqen-terraform-lib pull request #3
Opened 2023-03-24 13:50 UTC by PierreJiji

2023-03-24 20:13 UTC, gagf01 commented on aws/sea-backup/variables.tf
> +}
Est-ce qu'on pourrait avoir une variable enum qui dit le genre de ressource qu'on backup au lieu d'un bool et un arn par type? Si jamais nous voulons ajouter un autre type de ressource supporté par Backup, nous pourrons utiliser les mêmes variables.

Genre:
ressource_type = [rds|efs]
ressource_arn = [string]

2023-03-24 20:15 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/variables.tf
> +  description = "Quantité de stockage maximum pouvant être réservé en cas de mise à l'échelle du stockage (GB)"
Ajuster

2023-03-24 20:16 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/outputs.tf
> +output "rds_db_deploy" {
Je ne suis pas certain de comprendre à quoi sert ce output.

2023-03-27 18:13 UTC, PierreJiji commented on aws/sea-backup/variables.tf
> +}
J'ai fait la correction dans ce commit: fe3c8a26c09cc78dbfb24a14da78e5aa56e886f0
Ton idée d'avoir resource_arn, je le trouve très bon mais en même temps l'efs est une liste d'arn donc c'est un peu différent de celui de rds mais je vais regarder encore comment je peux améliorer cela..

2023-03-27 18:18 UTC, PierreJiji commented
> Super dans l'ensemble. Pourrais-tu ajouter des exemples d'utilisation du backup dans l'exemple svp?

Oui, bonne idée, je peux faire l'exemple qui va compléter ton exemple aussi de aurora

2023-03-30 13:27 UTC, gagf01 requested changes
Quelques ajustements à faire aux noms de variables et on pourra pousser le PR.

2023-03-30 13:27 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/outputs.tf
> +output "rds_db_deploy" {
Il faudrait donner un nom à la variable qui décrit la ressource plutôt que l'utilisation que tu en fais.

2023-03-30 13:27 UTC, gagf01 commented on aws/sea-backup/main.tf
> +  resources       = var.ressources_arn
Est-ce le bon nom de variable?

2023-03-30 13:27 UTC, gagf01 commented on aws/sea-backup/variables.tf
> +  type        = list(string)
Je ne répéterais pas le mot backup dans les noms de variables.

2023-03-31 17:41 UTC, PierreJiji commented on aws/sea-backup/main.tf
> +  resources       = var.ressources_arn
Non c'est une erreur et je viens de le corriger 296901f7dff9b046272814ef24e3fa817ee85287

2023-03-31 17:41 UTC, PierreJiji commented on aws/sea-backup/variables.tf
> +  type        = list(string)
296901f7dff9b046272814ef24e3fa817ee85287

2023-04-17 14:09 UTC, gagf01 requested changes

2023-04-17 14:09 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/main.tf
> +  vpc_security_group_ids              = var.vpc_security_group_ids
Ajouter par défaut les security_group data et ajouter ceux spécifiés en paramêtre.

2023-04-17 14:09 UTC, gagf01 commented on aws/sea-rds-aurora-mysql/outputs.tf
> +output "rds_db_deploy" {
Est-ce que la variable pourrait être renommée "rds_cluster_instance"?

2023-05-15 15:22 UTC, PierreJiji commented on aws/sea-rds-aurora-mysql/outputs.tf
> +output "rds_db_deploy" {
@yonepv Veux-tu dire la différence entre db_password_secret et rds_db_pass ? Si c'est la question, la différence est la suivante :
db_password_secret est l'ARN d'un mot de passe stocké dans le Secret Manager.
rds_db_pass est le résultat direct du mot de passe généré automatiquement dans le script.
Étant donné que je ne suis pas en mesure d'utiliser le Secret Manager dans le cluster EKS, j'ai utilisé la sortie (output) de random_password.

2023-05-15 15:23 UTC, PierreJiji commented on aws/sea-rds-aurora-mysql/outputs.tf
> +output "rds_db_deploy" {
@gagf01 le changement est déja faite aa58ed5d532333e3de75c8ba997770ef80ad6369

2023-05-15 15:44 UTC, PierreJiji commented on aws/sea-rds-aurora-mysql/main.tf
> +  vpc_security_group_ids              = var.vpc_security_group_ids
le code a été corrigé 0efed5b93973b01682814b3c0717c164e85a464c

2023-05-15 20:19 UTC, gagf01 approved these changes

2023-05-17 13:59 UTC, yonepv requested changes
Quelques petits ajustements et c'est prêt pour l'approuver

2023-05-17 13:59 UTC, yonepv commented on aws/sea-backup/README.md
> +
Petite descriiption pout continuer avec le format existant?

2023-05-17 13:59 UTC, yonepv commented on aws/sea-rds-aurora-mysql/variables.tf
> +  description = "Une groupe de sécurité supplémentaire associé à RDS"
```suggestion
  description = "Un groupe de sécurité supplémentaire associé à RDS"
```

2023-05-17 13:59 UTC, yonepv commented on aws/sea-rds-aurora-mysql/variables.tf
Il faut ajuster la description de la variable max_capacity et ensuite régénérer le readme.

2023-05-17 14:02 UTC, yonepv reviewed
Il manquerait aussi l'exemple pour ce module avec les vars terraform (comme fait pour aws-sea)

2023-06-21 14:06 UTC, yonepv commented on aws/sea-rds-aurora-mysql/README.md
> +| <a name="input_max_capacity"></a> [max\_capacity](#input\_max\_capacity) | Capacité minimale provisionnée en ACU (Aurora Capacity Unit, 0,5ACU = 1GB RAM) | `number` | n/a | yes |
```suggestion
| <a name="input_max_capacity"></a> [max\_capacity](#input\_max\_capacity) | Capacité maximale provisionnée en ACU (Aurora Capacity Unit, 0,5ACU = 1GB RAM) | `number` | n/a | yes |
```

2023-06-21 14:09 UTC, yonepv approved these changes

2023-06-21 14:10 UTC, merged